version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout

      - run:
          name: Install docker-compose
          command: |
            pip install --upgrade pip
            pip install docker-compose
      - run:
          name: Run tests
          command: |
           ./scripts/test
